### ISSUE TITLE
Add the old list view back

### ISSUE THREAD

**Issue by ljmerza** [hacs/integration#1239]
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

The new "card" view for the list of installed integrations/frontend is nice to look at but is not very practical. At least allow me to show the old table list view. With this new view I have to look all over the place to find what I'm looking for vs just looking down a list in a single column.

**Comment by ben8p** [comment]
I also prefer the old list.
Less fancy but more usable.
I miss the separation between cards and theme...
And with bugs like install button missing, that's a real pain...

**Comment by titomontes** [comment]
One more here. Please give us teh option to select the interface.

Also, this new interface is not mobile friendly, and there´s no way to only view my installed integrations, for example.

Cheers

**Comment by bartjekel** [comment]
I also prefer the old view. Things that I preferred from the old view:
- See what new components have been added.
- Separation between cards and views. They have a separate purpose, a card adds functionality and a theme changes the colors.

The UI has changed a lot of times already in the past. It feels like they're major overhauls each time instead of evolve into something better.

**Comment by ludeeus** [comment]
Don't derail feature requests, by adding unrelated requests and issues to it.
Open separate issues/feature requests for that, thanks 👍

**Comment by azrael783** [comment]
I would also appreciate to have the old style back.

**Comment by jeffh0821** [comment]
I'm not sure why all the previous comments were marked off-topic or spam. They certainly are not.

I respect the desire of @ludeeus  and others to give HACS as much of a "HA-integrated" feel as possible, but I'm afraid this might have gone too far. You took an exceedingly clean interface, with the best aspects of using cards, and threw it away in order to mimic the HA configuration interface. Now it's confusing and giant waste of space to do even mundane upgrades. The HA configuration interface is probably an OK single use case - but I would hate to see it replicated over and over and over again.

Please, reconsider this path. Or, just give up the separate interface altogether and figure out how to directly integrated in the base HA configuration interface.

For me - I loved and miss the prior interface. I would have preferred HA go in YOUR direction. Cards are so en vogue right now - but this too shall pass.

**Comment by ludeeus** [comment]
Like all other FR's, "same here" comments or does not add to the proposal are marked as "spam" (adding 👍  to the initial post is the way to do it.)
Comments that are not really related to the proposal are marked as "off-topic"

**Comment by ljmerza** [comment]
@jeffh0821 I absolutely agree. I hate the new card interface fad in general. Usability is suffering over "looking nice" which is subjective here.

**Comment by ludeeus** [comment]
No, I will not "Add the old list view back", but implementing a new list view with similar information, maybe in the future, this is not high on my list of things to do right now.

**Comment by jeffh0821** [comment]
Might as well close this FR. Was addressed and killed in PR1227.

**Comment by ljmerza** [comment]
thanks for ruining a good thing

**Comment by ben8p** [comment]
It's not all bad...
The new ui was disappointing mainly because of the bugs it had.
But they were fixed quickly and now it's alright..
I still miss the themes/card separation but I can live without.

**Comment by Critical-Impact** [comment]
Is there a way you could switch between both? I don't see why it's not possible to have multiple views for the same data

**Comment by ludeeus** [comment]
PSA: https://github.com/hacs/integration/issues/1905
