### ISSUE TITLE
Return of the "update all" 

### ISSUE THREAD

**Issue by JPM-git** [hacs/integration#1254]
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [X] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea
Being able to upgrade all repository at once with one click, so this avoid opening multiple pop-ups to upgrade each component.

## Implementation
There used to be a "update all" componente every since version before 1.0, now with the latest version i have to go to each component and open, select update, wait for the pop-ip to close, and do the same for all the rest.

**Comment by ludeeus** [comment]
Due to a good amount of complaints from maintainers this will not be reimplemented.
Users would just click that, and therefore not see release notes (which contains breaking changes).
This resulted in stuff breaking.

**Comment by IronicBadger** [comment]
How about a checkbox style system to update multiple integrations at once? Manually updating 30+ integrations is incredibly tedious.

It is my problem if I update and break something without reading the changelog. Perhaps under an 'advanced mode' we could have this functionality back? I miss it dearly.

**Comment by etricky** [comment]
@ludeeus I fail to understand your logic on how not having the update all option will solve the problem of users not checking breaking changes. If users didn't saw the release notes before, they will continue not to see them even if they have to manually update each integration. 

My suggestion is that all integrations must follow semantic versioning (major, minor, patch) which is followed by most software programs and any new version that has a new major release does not get included in the update all option. If developers don't follow this rule it will be their problem to solve as you would have given them a way to notify users of breaking changes. Since it is not that frequent to have major versions, most of the times, the update all option would be sufficient. Integrations with new major versions would be have to be updated manually which, at least, would signal users to check the release notes before doing the update.

This is just my suggestion, perhaps, there may be another way to accomplish this, but I sincerely believe that the update all option is something most users truly appreciate and miss as it greatly simplifies the update process. Please, reconsider having the update all option available again.

**Comment by boesing** [comment]
I think the main issue is, that maintainers mostly does not follow semver.
I would love to have an "update all" button, if all versions are bc safe, but actually most of the packages are not. I understand why this got removed.

**Comment by timdonovanuk** [comment]
Having to manually click update on my 20+ integrations/frontend is not more likely to make me read the release notes.

Please reconsider adding this button.

**Comment by IronicBadger** [comment]
Any word from a dev? Having to click a dozen individual updates is silly.

**Comment by Mincka** [comment]
Silly proposal: would it be possible to create a custom_component that handles this with the HACS API?
