### ISSUE TITLE
A visual indicator for reboot with integration update

### ISSUE THREAD

**Issue by grahamw72** [hacs/integration#1262]
## Category

- [ ] Backend/Integration
- [x ] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

A good description of what you are suggesting.

Love the new UI guys, very clean.  So in the old UI if we updated an Integration we got a reminder to do a HA restart with a button to achieve the restart.  It would look really cool to have a card pop-up (just like a new integrations card now with a different colour bar) in the top left corner of installed integrations page i.e. card in column 1, row 1 with a red bar.

## Implementation

How do you see this beeing implemented?

In column 1, row 1 of the installed integrations page have a card pop-up (just like new integrations appear now in new UI) with a red top bar to remind us to do a restart of HA for integration to be implemented with a restart HA button or text inside the card.  If no integrations updated , no card.

Not sure if it is feasible but many thanks for considering this request.  Keep up the good work.

## Alternatives

Are there any alternative solutions or features you've considered?

**Comment by rccoleman** [comment]
I agree with this.  It's great that there's now some fine print when an integration is updated that a reboot is required, but having a persistent message show up on the first page when a restart is required would be another step in the right direction.  I also wish that the "restart" button could be brought back, even if a breaking change or config error might prevent a restart.  I understand how it's possible for a restart to be silently blocked, but I've been using HACS since the first public release and I have yet to have a restart blocked because of a new/emergent config error.  If the goal is to avoid having users complain that new functionality is missing due to a blocked restarts, it seems like that's focusing on a tiny minority of users while exposing the majority to the exact same issue - "I installed an update, where's the new functionality?" - when the need to restart isn't clear and easy to do.

**Comment by ludeeus** [comment]
Marking issues (restart required/not added to lovelace/ others?) as red (similar to updates/new) are planed, just not implemented yet.

**Comment by grahamw72** [comment]
Many thanks for the update mate, sorry that i jumped the gun on you. Again, love the new UI. Close if you deem necessary.
