### ISSUE TITLE
"Not loaded in Lovelace" -> display not loaded elements

### ISSUE THREAD

**Issue by martinhoess** [hacs/integration#1312]
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea
Mix of feature request and frontend issue

![image](https://user-images.githubusercontent.com/47973549/83970352-9fc1cc80-a8d5-11ea-93c0-58795e6ff8c7.png)

If HACS knows that there are not loaded elements, it would be nice if the not loaded elements would be listed

A good description of what you are suggesting.

## Implementation

List every not loaded element below the message

**Comment by rccoleman** [comment]
You can see the items in the Frontend section like this:

![82A8C262-5100-4A33-9240-636E729BBDB7](https://user-images.githubusercontent.com/860888/83970657-b0e5eb80-a88b-11ea-9207-80468447b766.png)

**Comment by balthisar** [comment]
Except now that this is rolled in, it's showing this for _all_ of my installed HACS. They _are_ loaded, so the message is a lie.

I wonder if this is related to adding new front end stuff to HASS with the wrong path? HACS always tries to default resources to some stupid path, instead of /local/community, so maybe this false alarm is because it's looking in the garbage path instead of /local/community?

Apparently, the update no longer automatically adds new things to resources, so I don't recall that garbage path that HACS has been setting for me upon front end installs.

**Comment by JAAlperin** [comment]
Not loaded in Lovelace
You have 17 Lovelace elements that are not loaded properly in Lovelace.

All views and cards show properly.  Refresh and Reload Resources have no impact.

Not a useful addition to HACS.

**Comment by lancelon** [comment]
aaah this is such a pain!! I changed over the URL to /hacsfiles/ prior to updating and none of the resources are loading...
