### ISSUE TITLE
Possible issue with installation through Firefox

### ISSUE THREAD

**Issue by Gerw88** [hacs/integration#1395]
Might not be helpful, but during install, I was not able to find HACS on the Integrations page, despite restarting HA, clearing browser cache, reloading browser tab.
Tried the command line install (didn't see it first time), but saw no difference after clearing cache/restarting HA and FF. (Also verified that I hadn't made any mistakes in copying in my first attempt, which it seems I didn't)
I then loaded up Chrome and was able to find in in the Integrations tab first time. I entered my Github token when prompted, and noticed it appear in both Chrome and FF.

Firefox Browser 78.0.2 (64-bit)
OSX 10.13.6
Home Assistant 0.112.4 (running on a Pi 3 Model B)
HACS Release 1.2.2

**Comment by ludeeus** [comment]
If you do not see it in the list of addable integrations there is only 3 things that can do that:

- You are running Home Assistant version < 0.97
- You did not copy over all the required files to the expected directory.
- The browser cache is not fully flushed.

Closing this since there is nothing that can be done in HACS to remedy any of these
