### ISSUE TITLE
cbulock/lovelace-battery-entity

### ISSUE THREAD

**Issue by Morphy99** [hacs/integration#1464]
Inactivity (March 2020), now implemented in HA apart from battery icon colour doesn't change.

_This template should **only** be used if a repository **needs** to be removed/blacklisted from HACS_

**Comment by sibbl** [comment]
Are there any details why this was abandoned? It works properly for lots of people as far as I see?

**Comment by sibbl** [comment]
@Morphy99 @ludeeus as I haven't got any response in the last weeks, I'm trying to ask you my question again: are there any details why this plugin has been blacklisted?

If you ask me, it can't be the purpose of this project to blacklist plugins without any communication so that users have to fork the plugins to continue using them. Because that is what is happening right now...

**Comment by Morphy99** [comment]
I think I flagged it as most of the functionality is now available in HA core and there didn't seem to be any active development on it and a lot of open issues with it. I can't remember precisely what my issue was with it now, sorry. I'm happy for the blacklist to be removed if it's working fine for others @ludeeus
