### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by abacao** [hacs/integration#1473]
Steps to reproduce:

Fresh install HA HassOS 4.12 v 235
Activate Advanced Mode
Use Supervisor to install SSH & Terminal
Open terminal inside HA and paste the command line
```
curl -sfSL https://hacs.xyz/install | bash -
```
Reboot

Go to configuration, Integrations, Add

When searching for HACS, no HACS is found.

**Comment by ludeeus** [comment]
Clear your browser cache.
That is nothing that can be fixed/solved in HACS

**Comment by abacao** [comment]
Hello @ludeeus I have already cleared my cache and even installed a fresh new browser just to debug this.

The issue still persists:
![no_hacs_found](https://user-images.githubusercontent.com/17479246/90625165-10a82d80-e211-11ea-9a90-aa09604c6d8f.png)

**Comment by ludeeus** [comment]
There are only 3 things that can cause that
1) Files are not in the correct place (You used the script so that does not apply)
2) Home Assistant was not restarted after the files were put in the correct place (you stated that you rebooted the server)
3) Browser cache is not cleared

With 1 & 2 covered, that just leaves 3.

**Comment by abacao** [comment]
I have "Join Beta Channel" in HA and rebooted.
HACS has is now available as an Integration.
:bow:

**Comment by CBR900RRR** [comment]
Not sure if this is relevant to anyone else, but I couldn't get HACS to install, the log kept showing it was limited and waiting 80 secs etc.... the issue was that when I copied my key from GIT, there was a space at the end of the key, so it was failing to authenticate me but never actually prompted me that the key was wrong. bottom double check your key if it won't install.
