### ISSUE TITLE
kevinvincent/ha-wyzesense

### ISSUE THREAD

**Issue by RoldyBuffalo** [hacs/integration#1528]
[kevinvincent/ha-wyzesense](https://github.com/kevinvincent/ha-wyzesense)

64 open issue tickets on the repo, all nearly identical. The repo owner has not updated the integration in quite some time, and the last time doing so causing even more issue tickets to be created in the process. Now, the integration causes my hacs to not start up, the hub itself does not connect, and the sensors are all dead. Over $200 in assets laid to waste due to this integration not functioning as advertised, or even close.

_This template should **only** be used if a repository **needs** to be removed/blacklisted from HACS_

The repo is commonly installed by users seeking integration of their wyze sense sensors. The repo itself is stale from hassos standards, as well as the large amount of not responded to issue tickets, leads me to believe with clarification from the owner, they do not have time to manage the repo any longer, and will only be updating it with PR's.

**Comment by RoldyBuffalo** [comment]
I'm sad to see it go, but it's really hurting the image that hacs, and hassos is being given. Even in a small bit, people, myself included spent a sum of money on sensors to automate lights and door in our home. It worked fine, excellent in fact until recent changes from all directions have caused this repo / integration to fail set-up and installation on both my raspberry pi and intel nuc using proxmox and usb pass through, both usb 3.0 and 2.0.

**Comment by photinus** [comment]
Sorry to see you have not had a good experience with the component, and you're not wrong that it's not perfect. A large aspect of the issues is due to reverse engineering the hardware and relying on a library that was created then seemingly abandoned. It also does not help the situation that there are hardware issues (the 00000000 macs and unpairable sensors so far can only be attributed to failed hardware in the sensor). 

We'd welcome a PR with any improvements on the component though. I don't see any issues opened from you on the repo, would like to know more about the errors/issues that are causing your problems, I cant guarantee myself or anyone else that does what limited work we have time for can fix them, but we cant help if you don't ask/share your issues.

**Comment by ludeeus** [comment]
The repo in question does not seem abandoned, you should as @photinus said open issues so they can be looked at.
Closing this request for now.
