### ISSUE TITLE
Add support for pyscript scripts, apps, and modules

### ISSUE THREAD

**Issue by raman325** [hacs/integration#1569]
## Category

- [x] Backend/Integration
- [ ] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contains 1 request (if you have multiple open multiple feature requests).

## The idea

HACS already allows you to install AppDaemon and NetDaemon apps as well as `python_scripts`. `pyscript` is a new contender for building automations outside of HA's native YAML configuration and it would be great if users could download custom scripts/apps/modules that others have created and shared through HACS.

I'm not sure how much work would be required for this - I have not been able to find any published `pyscript` apps on GitHub so there may not be an ecosystem for this yet, but perhaps adding this support would encourage the creation of one.

## Implementation

Given that there's an existing model for NetDaemon and AppDaemon, I would suggest the same model is followed for `pyscript`, where there is a configuration option available to enable pyscript app discovery and tracking. Once it is enabled, results would show in the `Automation` section with the `pyscript` tag.

## Alternatives

Using GitHub and topics to find other user built pyscripts.

**Comment by raman325** [comment]
Looking at other requests for additional categories, this request may be premature since, as I had mentioned, there isn't really an ecosystem for `pyscript` yet. I will leave this open in case any maintainer sees the value, but I am also ok with this being closed for now and reopened in the future if an ecosystem does develop

**Comment by dlashua** [comment]
I think it's a chicken-and-egg situation. If it's in HACS, that will be the ecosystem. Without HACS, people can share manually, but it's more difficult. So methods other than HACS get employed to make it easier to share, at which point, there is an ecosystem, but, then, HACS is less needed since methods to share have been developed.

Without HACS, the easiest way to share is "cd pyscript/apps/; git clone somethingsomething ./app_name". But WITH HACS, that git directory structure no longer makes the most sense because the repo could be more specific about where the files should exist.

I'll give this some more thought as I try to flesh out how this should work. But, as I imagine you did, letting HACS handle it was my first thought.

**Comment by ludeeus** [comment]
PSA: https://github.com/hacs/integration/issues/1905
