### ISSUE TITLE
Error message after update

### ISSUE THREAD

**Issue by bertiebeez** [hacs/integration#1821]
I updated the HACS component in HA and now I get this error message and I am not sure how to fix this. It will not load any integrations either. I restarted my browser but it did not do anything different.

Information
Unexpected frontend version
You are running version 20201205162459 of the HACS frontend, but version 20210103144316 was expected, you should clear your browser cache.

**Comment by ludeeus** [comment]
Something is still cashing the old frontend.

These have been identified:

- uBlock Origin
- Browser (some had to open dev-tools and reload with it open)
- Cloudflare / Proxy

Try looking into those, since when you get that message, you have the new version of the frontend installed, your browser is just not using it (because of cache somewhere.)

**Comment by bertiebeez** [comment]
The browser cache was the issue.
Thank you for the quick reply and the help.

Sent from Mail for Windows 10
