### ISSUE TITLE
Allow installation of older versions with lower requirements

### ISSUE THREAD

**Issue by ludeeus** [hacs/integration#2170]
### Discussed in https://github.com/hacs/integration/discussions/2169

<div type='discussions-op-text'>

<sup>Originally posted by **mdeweerd** August 26, 2021</sup>
Upon trying to install a backup integration proposed in HACS, I was unable to add it because I am not running the beta version of HACS:

![image](https://user-images.githubusercontent.com/1504752/130963541-2ba80d07-7ca1-45ef-ac0c-e0ccff1f357b.png)

I tried selecting an older version of the integration, but apparently only the latest prerequisite(s) are checked.

The above example is for:
<html>
<body>

Version | core-2021.8.8
-- | --
Type d'installation | Home Assistant OS

</body>
</html>

The minimum version was fixed only recently for this integration:
https://github.com/jcwillox/hass-auto-backup/commits/master/hacs.json

The feature would be that the minimum required version is the one required in hacs.json for the (older) version that is to be installed.
</div>

**Comment by alandtse** [comment]
Discussion link is dead btw.

I just realized I need this feature too. I hadn't realized the hac.jsons HA key was for the entire repo and wasn't tied to the HACS.json at the relevant version tag. To give flexibility, it'd be great if the min was checked at the relevant tag. 

It's been a year or so since I last looked at the HACS code, but if this is acceptable behavior, I can see if I can figure out a PR.

**Comment by ludeeus** [comment]
Please don't, I'm transitioning all API calls to a more modern interface.
When that is done for fetching this file it will be implemented.
