### ISSUE TITLE
Request for removal of Limych/ha-average

### ISSUE THREAD

**Issue by Doonga** [hacs/integration#2654]
### Repository

Limych/ha-average

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Author apparently isn't maintaining this any more and it's broken in the new version of HA.

### Link to issue

https://github.com/Limych/ha-average/issues/129

**Comment by lmagyar** [comment]
Currently there is a fix for this issue, though the original repo's owner "disappeared", should I ask to add my fork to HACS instead of the original repo until the original repo gets revived?

**Comment by DavidFW1960** [comment]
It may be that Limych being Russian cannot update this component too so I think requests for removal are premature to say the least.

**Comment by lmagyar** [comment]
Yes, I was thinking the same. Though he has some commit activity on other repos. Though those are mainly dependency update level smaller fixes...
Now I wrote him an email, asking about the situation/plans/anything.
>Hi!
>I’m a plain user of this HA integration and I’m asking what are your plans with this integration?
>Currently this integration is broken with the newest HA release 2022.5.x. I made some fix/workaround to keep it alive, but the latest HACS uploaded version is still broken and there are no activities on this repo in the past several months.
>Most of us concerned maybe the current “situation” in Europe keeps you away maintaining it. So what do you suggest, how should things go forward?

**Comment by Limych** [comment]
@lmagyar, thank you for request my attention for this situation.

Yes, because of situation across Russia I have very less free time to update my repos. But I've not abandon them.

If you, @lmagyar, could please open PR with bugfixes, I'll approve it. But you dosn't do it yet...

And I myself can't make now accurate bugfix because I can't run tests because are broken docker images for devcontainer maden by @ludeeus, which is used in tests.

I've open new issue to fix docker images (https://github.com/ludeeus/container/issues/292) and I hope @ludeeus fix this problem soon.

**Comment by lmagyar** [comment]
Thank you for the quick response. :) I've already tested the new release, and it works. I think this issue can be closed, no need for removal.
