### ISSUE TITLE
HACS sensor reports 20 updates upon startup

### ISSUE THREAD

**Issue by mat4444** [hacs/integration#2700]
## System Health

version | core-2022.5.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.15.32-v7
arch | armv7l
timezone | America/New_York

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4349
Installed Version | 1.25.1
Stage | running
Available Repositories | 1076
Downloaded Repositories | 35

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.1
-- | --
update_channel | stable
supervisor_version | supervisor-2022.05.3
docker_version | 20.10.14
disk_total | 57.8 GB
disk_used | 9.3 GB
healthy | true
supported | true
board | rpi3
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Samba share (9.6.1), Check Home Assistant configuration (3.10.0), ADB - Android Debug Bridge (0.7.0), SSH & Web Terminal (10.1.3), deCONZ (6.13.0), Log Viewer (0.13.0), Duck DNS (1.14.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 16
views | 6
mode | yaml

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Since 1.25.1, HACS reports about 20 updates upon reboot of Home Assistant.
A few seconds later, the problem is fixed, and the values reads 0.
However, the erratic value triggers my update notification automations.

![image](https://user-images.githubusercontent.com/53400792/170406727-e811f066-e121-46fd-871e-f20421926216.png)

### Reproduction steps

1. Make sure HACS version is 1.25.1
2. Reboot Home Assistant
3. Read sensor.hacs
4. Notice the value is close to 20 upon reboot, then goes back to 0

### Debug logs

```text
http://pastebin.fr/106194
```

### Diagnostics dump

http://pastebin.fr/106193

**Comment by DavidFW1960** [comment]
Is this an issue? When the attributes were broken in the last update it didn't do this but does now. It won't do it if you enable experimental features in HACS. Maybe look at your automation and only trigger is the sensor is >0 for a couple of minutes?

**Comment by regevbr** [comment]
I have the same issue - I just changed my node red logic to `>0 && < 20`...

**Comment by uherting** [comment]
I experience the same issue with latest HA supervised and HACS.

I got an automation which ran fine so far but now it notifies my that literally all my installed integrations and front end stuff has an update. The version of these "updates" comes along as the hex commit reference string from github instead with the ordinary x.y.z . My automation can be found at https://github.com/uherting/MyHA-Configuration/blob/master/conf/automations/hacs_updates_pending.yaml . The sensor sensor.hacs seems to change at startup in such way that I get 20+ notifications while the state of the sensor is seemingliy decreasing.

Since today in the afternoon HACS itself offers two updates where the version comes along the hex history string instead with the ordinary x.y.z. I cannot get them updated through clicking on the update button though.

In the dev tools I got the following information on sensor.hacs. The state equals to 2 and the attribute repositories reads as follows.

repositories: 
- name: maykar/lovelace-swipe-navigation
  display_name: Lovelace Swipe Navigation
  installed_version: 1.3.6
  available_version: 168e0e3
- name: maykar/kiosk-mode
  display_name: Kiosk Mode
  installed_version: 1.7.2
  available_version: 5c29a5a

I hope this helps to solve the problem.
