### ISSUE TITLE
missing 3 dots

### ISSUE THREAD

**Issue by goldbe4804** [hacs/integration#2797]
### Web browser

edge

### Web browser version

Version 103.0.1264.62

## System Health

version | core-2022.7.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.32-v8
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 3983
Installed Version | 1.26.2
Stage | running
Available Repositories | 1143
Downloaded Repositories | 18

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.2
-- | --
update_channel | stable
supervisor_version | supervisor-2022.07.0
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 109.3 GB
disk_used | 13.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), Terminal & SSH (9.6.0), File editor (5.3.3), Home Assistant Google Drive Backup (0.108.2), Node-RED (13.0.0), Mosquitto broker (6.1.2), Z-Wave JS (0.1.64), ESPHome (2022.6.2), SSH & Web Terminal (11.0.2), ESPHome (dev) (dev), TTLock (0.4.11), TTLock2MQTT (0.5), Uptime Kuma (0.1.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 4
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 8, 2022 at 10:00 AM
-- | --
current_recorder_run | July 15, 2022 at 8:36 AM
estimated_db_size | 729.66 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

my installed adons are all missing the 3 dots so i cant reload, uninstall.....so on

### Reproduction steps

1.open hacs
2.open frontend
3.go down to addons 
...

### Screenshots

![dots](https://user-images.githubusercontent.com/56876314/179554369-6495c294-eb6f-4774-b591-966e9518edde.JPG)

### Javascript logs from your browser console

```text
n/a
```

**Comment by ludeeus** [comment]
Correct. It’s moved.
See docs for whatever you wanted for it.

**Comment by goldbe4804** [comment]
sorry can you tell me were its moved to or were to find the docs -- everything i am finding still show the dots !!! thanks !!

**Comment by bobofruit1970** [comment]
So as not to keep multiplying brazen answers.
Many people ask where the three dots have gone and get no answer. Pity.
It worked, but it bothered someone, although it was obvious and transparent.
I tried to find where it was described in DOCS. I failed to. Maybe someone will send it where it is described.

Today, while trying to remove the integration, I destroyed the entire HA configuration and I will have to restore it from backup.

The dots have been moved to the integration page (top right menu)
And that's not a problem.
The problem is that I wanted to remove 5 integrations and remove HACS to reinstall it.
Three integrations have been removed in a new way and two do not want to be removed in this new way.
The only way I was able to remove unwanted integrations is to downgrade HACS to version 1.25.5 and remove with three dots
Then it worked.
I will leave a comment to those struggling with this problem. I lost half a day today.

Example: Adding and removing Bodymiscale integration.
Try to add Bodymiscale integration. As You can see there is no three dots in 1.26 version of HACS.

![image](https://user-images.githubusercontent.com/67933104/179603139-facaa687-8fb7-40e9-b458-196927616416.png)

Click on the integration and You will find in upper right corner menu with option to remove integration.

![image](https://user-images.githubusercontent.com/67933104/179603270-0acbce59-91d9-4a96-995c-c8b5b32b755b.png)

If You will happy it will work. If it will not work like in my HA You will have to downgrade HACS to 1.25.5 and You will see three dots and it will let you remove unwanted integration. 

After downgrading HACS to 1.25.5 You will see three dots.
Then You will be able to remove Bodymiscale integration
![image](https://user-images.githubusercontent.com/67933104/179605975-747444fd-c962-44ce-be10-dc6e58fb3829.png)

![image](https://user-images.githubusercontent.com/67933104/179606258-93a5dc68-c8f9-4eb2-aa3f-854be884476a.png)
