### ISSUE TITLE
Removal of Clever from integrations

### ISSUE THREAD

**Issue by MTrab** [hacs/integration#3196]
### Repository

mtrab/clever

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Has been dead for some time now, and have tried to have it removed before.
I have recently marked it archived

### Link to issue

https://github.com/MTrab/clever

**Comment by Taomyn** [comment]
I've been trying to get rid of this since a few releases, even trying experimental features, yet every time I restart either HA or just HACS they both come back as new

![Screenshot_20230722-033248.png](https://github.com/hacs/integration/assets/4365929/5bdf63ec-1c91-4a51-a767-4178723a56b1)

![Screenshot_20230722-033259.png](https://github.com/hacs/integration/assets/4365929/9be8211a-4fb4-413b-ac11-b7b53e984042)

![Screenshot_20230722-033317.png](https://github.com/hacs/integration/assets/4365929/71783cac-3907-4c1c-9b43-def7bb40f565)

**Comment by ludeeus** [comment]
Restart Home Assistant (, or wait 6h), and it's gone.

**Comment by Taomyn** [comment]
> Restart Home Assistant (, or wait 6h), and it's gone.

Makes no difference, the two just come back each and every time.. I've added removed other integrations for tests and they work fine.

**Comment by ludeeus** [comment]
If it does not make a difference, then you have not really restarted Home Assistant (I assume this is what you did as you can not have waited 6h, as it has not been > 6h since my message).

**Comment by Taomyn** [comment]
> If it does not make a difference, then you have not really restarted Home Assistant (I assume this is what you did as you can not have waited 6h, as it has not been > 6h since my message).

And how would you know any of that? The HA has been completed rebooted 3 times, including both the HA service and the HA host, just this week for other reasons and as I already stated, each and every time these two integrations just come back.

**Comment by ludeeus** [comment]
I know that because it has been removed.
> just this week

That does not say that you have done it *after* my message..

**Comment by Taomyn** [comment]
> > just this week
> 
> That does not say that you have done it _after_ my message..

So you do now
