### ISSUE TITLE
Request for removal of oziee/ha-solcast-solar

### ISSUE THREAD

**Issue by ghost** [hacs/integration#3745]
### Repository

oziee/ha-solcast-solar

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

I own it. Remove it

### Link to issue

I own it. Remove it

**Comment by Speshman** [comment]
Can I ask why oziee? It's a massively useful repo that will be very sorely missed

**Comment by oziee** [comment]
Because I have had enough of the BS I personally receive from users in msgs and I no longer wish to support such a bunch of self righteous ppl that demand they get what they want, don't bother to read changes and then just post the same shit over and over. The amount of abuse for temp removing a basically insignificant sensor as the api counter in the last day sealed the fate I have better things to do in life

**Comment by Speshman** [comment]
I understand, I saw some of the comments a few days back and they were pretty awful.

Would you consider putting it back up and archiving it? Perhaps someone would fork it and continue your good work (I lack the ability to do so unfortunately).

**Comment by johny-mnemonic** [comment]
@oziee first I would like to thank you for such a great integration and for all the work you did for the community! It was really immensely useful and there are a ton of people who admire your work.
It is sad that some people are so stupid to even attack you...that's a disgrace 😢 

I completely understand you don't want to be attacked by those haters and you have all the right to stop supporting your code.
On the other hand, by removing the code completely you are doing the most harm to the people that appreciate your work and always supported you and were grateful. Those haters, they won't care. Unfortunately haters are the most visible and loud, not the ones who are happy and grateful...

So I am joining @Speshman with the plead to return the repo and putting it into archived state so if anyone brave decides to continue with the great work you have done for all of us he can do that.

Wish you all the best no matter what you decide to do!

**Comment by oziee** [comment]
There are plenty of forks out there and everyone has a copy in their ha/config/components/ha-solcast-solar for 😀 

Easy for someone to start again

**Comment by BJReplay** [comment]
Dude, I get why you'd like to remove it, but by pre-emptively taking your repo private, you've broken everyone's repo who is using.  If you restart HA, it won't re-start.

At least make your repo public until this is completed, please?

**Comment by thewookiewon** [comment]
@oziee completely understand you're position and online trolls / bully comments can be detrimental.

How've don't let the trolls win, could the project be publically archived and let someone else continue your good work instead?

**Comment by bbrks** [comment]
> taking your repo private, you've broken everyone's install who is using. If you restart HA, it won't re-start.

That very much seems like a HACS problem.

**Comment by BJReplay** [comment]
> That very much seems like a HACS problem. File an issue for that behaviour and maybe we (the collective community) can try to fix that fundamental flaw.

I think HACS has the ability to deal with dead repos - while trying to get HACS restarted, I've found hacs.hacs in the .storage folder - that lists archived repos.  I imagine this allows still working but archived repos to keep working.

The issue is that, until a repo has been added by HACS to this list, users are SOL.

**Comment by Petro31** [comment]
> Dude, I get why you'd like to remove it, but by pre-emptively taking your repo private, you've broken everyone's install who is using. If you restart HA, it won't re-start.
> 
> At least make your repo public until this is completed, please?
> 
> https://github.com/oziee/solcast-pvsolar/issues/1

Oziee deleted his github account, that's not an option.  He's in the process of deleting his forum account too.

**Comment by BJReplay** [comment]
> Oziee deleted his github account, that's not an option. He's in the process of deleting his forum account too.

He hadn't earlier this evening, but has now.

It was an option when I wrote that.

Sadly not any more.

What a massive dummy spit to leave people with broken, unstartable HA installations.

**Comment by bbrks** [comment]
Completely breaking HA installations because of something disappearing is _not_ the fault of the disappearing thing. That will inevitably happen.

Let's figure out how to solve that HACS problem instead of brigading against a burnt-out developer that has provided countless hours of free work and rightfully decided to throw in the towel in the way they see fit.

**Comment by BJReplay** [comment]
> Let's figure out how to solve that HACS startup problem

Agreed.  I'm all ears for any suggestions.  I've tried everything that I can think of:

- Back up all of the files in the .storage directory that reference the integration before removing traces of it.
- Remove traces of the integration from those files, and from the custom_components directory

But I think there are references - possibly in the database that I can't get at, so when I restart, it still hangs.

I think that HACS needs to complete **this** process - flagging this repo - so that HACS marks it as dead (via an entry in hacs.hacs) - and so HA can clean up the database.

I've tried creating an entry in hacs.hacs, but it looks like HACS pulls that down on every start (obviously).

I don't know, but I think that's how it cleans up.

All I know is that I'm sick of seeing all the WARNING messages, followed by 
```
2024-05-31 21:12:23.764 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-31 21:12:23.764 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration spook which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-31 21:12:23.764 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

```

followed by ERROR

`2024-05-31 21:12:23.764 ERROR [custom_components.hacs] <Integration oziee/ha-solcast-solar> GitHub returned 404 for https://api.github.com/repos/oziee/ha-solcast-solar`

Once this is sorted, and I've got HA running, my first port of call will be to create a new Solcast Integration.

The second thing I'll do (via my self-hosted AdGuard) is prove that if the github repo is unreachable, HACS won't start, and then I'll raise an issue on HACS.

**Comment by PianSom** [comment]
This is a naive suggestion, so please feel free to disregard. But desperate times ...

Theory - It may be that the startup error is caused by the failed call to https://api.github.com/repos/oziee/ha-solcast-solar

Potential solution - A user has already created a fork at https://github.com/Dehumanizer77/ha-solcast-solar . So it may be worth setting up a new instance of HA, installing HACS, installing that repository, then calling the API. Then use the results of that API call with your Adguard to feed in to your original HA instance. If it starts up (HUGE if) then add in that repo to your HACS. 

See https://community.home-assistant.io/t/solcast-global-solar-power-forecast-integration/334681/291

**Comment by laurencei** [comment]
> but by pre-emptively taking your repo private, you've broken everyone's install who is using. If you restart HA, it won't re-start.

Does this also mean if HA cant reach github - i.e. github is down, then would that have the same effect for any HACS that relies on github?

I'm confused why HACS has a dependency on the repo been present or not at all....

**Comment by johny-mnemonic** [comment]
Not sure why, but adding custom repo containing a for of the original one (and hence providing the same integration) does not work for me.
I can add it, but installation from it fails and after HA restart the custom repo is gone.
Is there an issue with the fact the two repos can't provide the same integration?

**Comment by tiaanv** [comment]
I had similar issues when developing and putting the source up on Git Hub for people to use... It's like people think because you've put it out there you have to maintain it for them, and how they want it..  I feel you...

That being said.  This one is a big loss, but I'm sure we can recreate this one from the ashes.  If someone wants to start a combined project and needs some dev help.  I am happy to chime in.  Contact me.

First task is to remove it form hacs, and simply manually install it as a custom component in HA.

**Comment by thewookiewon** [comment]
Almost feels like on the readme section a disclaimer note needs to highlight that developers do this freely for the community and without cost, be respectful, patience and read any existing issues/comments first.

**Comment by BJReplay** [comment]
> Theory - It may be that the startup error is caused by the failed call to

I was thinking this.

The problem is that the check also includes the hash, and the hash is maintained by HACS.

I am going to block list github and see if I can start HA

**Comment by BJReplay** [comment]
> I can add it, but installation from it fails and after HA restart the custom repo is gone.

HACS maintains a list of reps and hashs - no match, no go.

**Comment by BJReplay** [comment]
For anyone following along, https://github.com/BJReplay/ha-solcast-solar is ready to go for manual installation into HACS to replace the oziee repo.

Forked from https://github.com/Dehumanizer77/ha-solcast-solar as mentioned by @PianSom [above](https://github.com/hacs/integration/issues/3745#issuecomment-2142361402), I've replaced all links to oziee with BJReplay so this repo works properly as a manually added HACS repo, including updates, once installed.

I'm in the process of submitting to HACS.

**Comment by BJReplay** [comment]
> Does this also mean if HA cant reach github - i.e. github is down, then would that have the same effect for any HACS that relies on github?

If HACS can't reach GitHub, HACs can't start, it would seem.

**Comment by niggles1973** [comment]
@BJReplay  would be it be a good opportunity to deploy a randomised query time to force on the hour api queries to a random(10) or so seconds to take load off the solcast api

**Comment by BJReplay** [comment]
> would be it be a good opportunity to deploy a randomised query time to force on the hour api queries to a random(10) or so seconds to take load off the solcast api

PRs welcomed 🤣

Seriously, I was a developer 30 years ago, a software company owner 15 years ago, and retired a few years ago for health reasons. 

I barely know how to copy-pasta python.  The only code I currently maintain (badly) is in VB.NET. I shit you not.

If there are (or were PRs) or code snippets suggesting how to do it, or someone has a version doing this, year, I'm all up for incorporating it.

But I wouldn't know how to do it from scratch.

**Comment by wimdebruyn** [comment]
> Almost feels like on the readme section a disclaimer note needs to highlight that developers do this freely for the community and without cost, be respectful, patience and read any existing issues/comments first.

The irony is that Oziee's biggest issue is that people don't read the Readme.  The reality is that most people don't and won't.  It comes with the territory when you publish software.  Accept it, don't take it personally, and don't be nasty to people because of it.

**Comment by wimdebruyn** [comment]
> > would be it be a good opportunity to deploy a randomised query time to force on the hour api queries to a random(10) or so seconds to take load off the solcast api
> 
> @niggles1973 PRs welcomed 🤣
> 
> Seriously, I was a developer 30 years ago, a software company owner 15 years ago, and retired a few years ago for health reasons.
> 
> I barely know how to copy-pasta python. The only code I currently maintain (badly) is in VB.NET. I shit you not.
> 
> If there are (or were PRs) or code snippets suggesting how to do it, or someone has a version doing this, year, I'm all up for incorporating it.
> 
> But I wouldn't know how to do it from scratch.

@BJReplay , great job to get everyone up and running again.  Thank you.

I hope your addition PR is accepted soon.

**Comment by longzheng** [comment]
Just confirming I'm still able to restart HA successfully with the old integration installed. Both HACS and the Solcast PV Forecast integrations seems to load correctly, even though I do see the 404 error in the logs.

**Comment by DJBenson** [comment]
I never had the issue with not being able to restart and the old version was working still but I've switched to @BJReplay's version - thanks for picking up the baton.

**Comment by DJBenson** [comment]
> Almost feels like on the readme section a disclaimer note needs to highlight that developers do this freely for the community and without cost, be respectful, patience and read any existing issues/comments first.

The problem is the 99% of people who are grateful for these developers efforts will read it but it will be preaching to the choir and the 1% who can't even be bothered reading changelogs won't read the disclaimer either.

**Comment by KeithB** [comment]
> > would be it be a good opportunity to deploy a randomised query time to force on the hour api queries to a random(10) or so seconds to take load off the solcast api
> 
> @niggles1973 PRs welcomed 🤣
> 
> Seriously, I was a developer 30 years ago, a software company owner 15 years ago, and retired a few years ago for health reasons.
> 
> I barely know how to copy-pasta python. The only code I currently maintain (badly) is in VB.NET. I shit you not.
> 
> If there are (or were PRs) or code snippets suggesting how to do it, or someone has a version doing this, year, I'm all up for incorporating it.
> 
> But I wouldn't know how to do it from scratch.

For anyone wanting to take a look at this, the BottlecapDave Octopus Energy integration had some good changes for this - there was a rumour kicking around that HA integration traffic on its own was generating a decent % of their traffic. As you can see from [this ticket](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/597), Octopus reached out to the author and asked for a few changes...

Nice to see a company working with these things rather than blocking them!

**Comment by Stephens-ely** [comment]
For those wishing to 'randomize' their Solcast updates so that they don't all happen on the hour (as pointed out by KeithB) then a simple template trigger based on your Sunrise and Sunset can help offset when the updates occur. I use the Sun2 integration for Sunrise/Sunset so you'd have to modify this but...

alias: System - Update Solcast Data
description: ""
trigger:
  - platform: template
    value_template: >-
      {% set sr = as_datetime(state_attr('sensor.whitchurch_sun_rising','today'))|as_local %}
      {% set ss = as_datetime(state_attr('sensor.whitchurch_sun_setting','today'))|as_local %}
      {% set api_request_limit = 10 %}
      {% set hours_difference = (ss - sr) %}
      {% set interval_hours = hours_difference / api_request_limit %}
      {% set ns = namespace(match = false) %}
      {% for i in range(api_request_limit) %}
        {% set start_time = sr + (i * interval_hours) %}
        {% if ((start_time - timedelta(seconds=30)) <= now()) and (now() <= (start_time + timedelta(seconds=30))) %}
          {% set ns.match = true %}
        {% endif %}
      {% endfor %}
      {{ ns.match }}
condition: []
action:
  - service: solcast_solar.update_forecasts
    data: {}
mode: single

**Comment by ludeeus** [comment]
https://github.com/hacs/default/commit/0d792c884db4946355c6adec4aecebdf28740b72
