### ISSUE TITLE
Request for removal of Makin-Things/platinum-weather-card

### ISSUE THREAD

**Issue by Jeppedy** [hacs/integration#3974]
### Repository

Makin-Things/platinum-weather-card

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

It’s not just dormant, it doesn’t work after a not-so-recent HA breaking change to weather handling.

### Link to issue

See the entire site

**Comment by BJReplay** [comment]
@ludeeus although the card isn't actively maintained, I'm not convinced that the reason for removal given is valid - the card is working for me (and, I'm guessing for a lot of other people as well) - it works well for people in Australia using the Bureau of Meteorology (BOM) weather source.

It may not work for a lot of people for sure, because of changes to weather sources, but this repo was created because of issues with other weather cards not working with the BOM weather source.  Given that there are other repos that do work - as mentioned in https://github.com/Makin-Things/platinum-weather-card/issues/110, I don't think one user's request to have it removed is a good reason to remove it for all users who are currently relying on it as one of the cards that works well for a large number of HA users.

Thanks for reading.

**Comment by AdamGit69** [comment]
As above, I use this for BOM and it works fine for me and as stated above, for many others in Australia as well. Please do not remove just because of one users request.

**Comment by BJReplay** [comment]
Thanks @Jeppedy for closing.
