### ISSUE TITLE
Ability to download default branch is gone.

### ISSUE THREAD

**Issue by JeffSteinbok** [hacs/integration#4009]
### System Health details

Unsure this is intentional, but the ability to download the default branch for a repository seems to be gone.

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Previous to v2.0, the option to download default branch would be present unless a repository blocked it.  

### Reproduction steps

1. Open HACS
2. Pick a repository (I used the Dreo one)
3. Try to download default branch; option not there.

### Debug logs

```text
N/A
```

**Comment by ludeeus** [comment]
It was extended and moved.
https://hacs.xyz/docs/use/entities/update/#install-action

**Comment by 5ila5** [comment]
So I can install the default branch version only by manually calling the action, and it's intentional to not show up in the installation menu anymore?

So if I need some new changes of an integration not yet part of a release I need to go to the integration install the latest version, go to the developer tools -> actions -> update install -> type in master (or default branch name) and run the action. Is there any reason you removed the default branch from the 'Need a different version' dropdown?

**Comment by ludeeus** [comment]
Its not a version.
And branches / commits should not be used unless the author tell you to do so (as noted in the docs)

**Comment by JeffSteinbok** [comment]
ACK - Understood.  As an integration owner, it was convenient for me to test and to ask a few other people to try something out before taking the time to publish a release.  Glad there is a workaround, but was nicer in the UX.
