### ISSUE TITLE
no scrollbar in community tab

### ISSUE THREAD

**Issue by 78wesley** [hacs/integration#777]
**Is your feature request related to a problem? Please describe.**
I see a scrollbar at the Community tab and it is a little bit annoying, It only moves 6 pixels. And it looks like it is a scrollbar of a <iframe> tag, In the picture below the this text you see at the bottom a little white bar. that is the bar what i mean. And I guess this <iframe> is from the Community tab not the one of "overview".

![image](https://user-images.githubusercontent.com/9322930/68977740-35dabc00-07f9-11ea-8466-5665ebb82f1e.png)

**Describe the solution you'd like**
When the content is not more then the screen size the scrollbar needs to be hidden. 

**Alternative solution**
Ignoring the scrollbar

I am using version 0.16.3 of hacs

**Comment by ludeeus** [comment]
That is nothing I'm able to control, HA sets the height used for the iframe.
Next version will not be a iframe so that "issue" is no longer there.

If you enable experimental features in HACS, you can get the new UI now.
https://hacs.xyz/docs/configuration/options#options
https://hacs.xyz/docs/configuration/legacy#options-map
