### ISSUE TITLE
Ability in within HACS to block a specific release

### ISSUE THREAD

**Issue by SeLLeRoNe** [hacs/integration#802]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Today the Places integration release had a bug which prevent HA to restart (indentation) and whoever is gonna install it will have issue with HA, while less experienced/knowlegeable people will have a non-working kind-of-hard-to-fix HA instance

**Describe alternatives you've considered**
HACS Staff (with or without user notification) should be able to mark a specific release for a specific component (integration/plugin/theme/python_script) to prevent the specified version to be "offered" as update to HACS users.
This will prevent a problem, when identified, to spread too much and cause too much "damage"

A blocked release should be somehow marked to show the user that it is not "allowed" to install that version (ex. Red Color on the version number)

**Additional context**

**Comment by VDRainer** [comment]
That would be cool.
Show the updates in the overview, but don't populate the sensor.

**Comment by ludeeus** [comment]
That would be something completely different @VDRainer this is about HACS not getting/showing a potentially faulty release at all, if you would like that create a separate feature request where you describe it.

**Comment by ludeeus** [comment]
I don't see a good way of implementing this.

Right now, the best action is to create an issue with the repo in question.
If that fails, it can be blacklisted from HACS, and in worst case forcibly removed https://hacs.xyz/docs/developer/maintainer#critical-repositories

I do not think I want to introduce another method to handle specific releases.
The maintenance tied to that will be too much work, and since humans are involved it will be flawed and not 100% reliable.
