### ISSUE TITLE
Configuration checking does not work when hacs is active

### ISSUE THREAD

**Issue by majdzik84** [hacs/integration#829]
I noticed that when HACS is loaded I can't check the configuration. Checking never ends.
When I remove hacs from config.yaml: everything returns to normal.
Has anyone noticed a similar problem?

I'm using hassio 0.102.2
I didn't notice anything in the logs

**Comment by DeviousPenguin** [comment]
How long do you leave it to check config? Are you using HASSIO or VENV?

**Comment by TorqueDelight** [comment]
Same here, `check-config` takes a few minutes to complete with this message in the logs:
`INFO:homeassistant.util.package:Attempting install of attrs==19.2.0`

When I comment out hacs from `configuration.yaml` check config takes a few seconds and I don't get this message in the log.

Very similar to this issue:
https://github.com/custom-components/breaking_changes/issues/16

**Comment by DeviousPenguin** [comment]
I get the exact same message @TorqueDelight, I'm running VENV and config usually takes ardound 5 seconds to check, but when HACS is enabled I get the 'Attempting install of attrs==19.2.0' message also and it takes around 10-15 seconds to check the config.

From looking at the source for HACS, I'm 90% sure this will be fixed in the next release of HACS.
